/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cars;

import clients.Client;
import clients.ClientCrudSystem;
import clients.ClientCrudSystemUI;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import authentication.Home;

/**
 *
 * @author Med Amine Ben Ammar
 */
public class CarCrudSystemUI extends javax.swing.JFrame {

    /**
     * Creates new form CarsCrudSystem
     */
    public CarCrudSystemUI() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) cars_data.getModel();
        for(Car list:CarCrudSystem.getAllCars())
        {
            Object[] row = { list.getId(), list.getMar() };
            model.addRow(row);
        }
    }
    
    
    public void setAdminInfo(String name)
    {
        c_admin_name.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cars_data = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mark = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        add_car = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        u_mar = new javax.swing.JTextField();
        u_id = new javax.swing.JTextField();
        u_res = new javax.swing.JButton();
        del_car = new javax.swing.JButton();
        find = new javax.swing.JButton();
        u_car = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        v_car = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        c_admin_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cars_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mark"
            }
        ));
        jScrollPane1.setViewportView(cars_data);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Cars", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mark");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 70, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("ID ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 40, 50));

        mark.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(mark, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 180, 50));

        id.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, 50));

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        reset.setText("Reset");
        reset.setToolTipText("");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 170, 70));

        add_car.setBackground(new java.awt.Color(255, 255, 255));
        add_car.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add_car.setText("Add Car");
        add_car.setToolTipText("");
        add_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_carActionPerformed(evt);
            }
        });
        jPanel2.add(add_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 170, 70));

        jTabbedPane1.addTab("Add Car", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Mark");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 70, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("ID ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 40, 50));

        u_mar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel3.add(u_mar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 180, 50));

        u_id.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel3.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, 50));

        u_res.setBackground(new java.awt.Color(255, 255, 255));
        u_res.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        u_res.setText("Reset");
        u_res.setToolTipText("");
        u_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_resActionPerformed(evt);
            }
        });
        jPanel3.add(u_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 170, 70));

        del_car.setBackground(new java.awt.Color(255, 255, 255));
        del_car.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        del_car.setText("Delete Car");
        del_car.setToolTipText("");
        del_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_carActionPerformed(evt);
            }
        });
        jPanel3.add(del_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 170, 70));

        find.setBackground(new java.awt.Color(255, 255, 255));
        find.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        find.setText("find");
        find.setToolTipText("");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        jPanel3.add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, 30));

        u_car.setBackground(new java.awt.Color(255, 255, 255));
        u_car.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        u_car.setText("Update Car");
        u_car.setToolTipText("");
        u_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_carActionPerformed(evt);
            }
        });
        jPanel3.add(u_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, 70));

        jTabbedPane1.addTab("Update / Delete", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("ID :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 50));
        jPanel4.add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 50));

        v_car.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        v_car.setText("Car File");
        v_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_carActionPerformed(evt);
            }
        });
        jPanel4.add(v_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 180, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_diag.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 150, 130));

        jTabbedPane1.addTab("Car File", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 690, 390));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_pic.png"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 70));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("Admin Name : ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, 60));

        c_admin_name.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        c_admin_name.setText("jLabel12");
        getContentPane().add(c_admin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 110, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 70, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        id.setText("");
        mark.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void add_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_carActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String t_id = id.getText();
        String _mark = mark.getText();
        
        int _id = Integer.parseInt(t_id);
        
        
        Car car = new Car(_id, _mark);
        Car test_existence = CarCrudSystem.getCar(_id);
        
        if(test_existence.getId()== 0)
        {
           int status = CarCrudSystem.save(car);
            if(status > 0)
            {
                JOptionPane.showMessageDialog(jPanel3,"Record Added succesfully");
                this.setVisible(false);
                CarCrudSystemUI ui = new CarCrudSystemUI();
                ui.setAdminInfo(c_admin_name.getText());
                ui.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(jPanel3,"Sorry! Error Occured","Warning",JOptionPane.ERROR_MESSAGE);
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(jPanel3,"Valeur du ID Dupliquer","Warning",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_add_carActionPerformed

    private void u_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_resActionPerformed
        // TODO add your handling code here:
        u_id.setText("");
        u_mar.setText("");
        u_id.setEditable(true);
    }//GEN-LAST:event_u_resActionPerformed

    private void del_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_carActionPerformed
        // TODO add your handling code here:
        String t_id = u_id.getText();
        int id = Integer.parseInt(t_id);
        
        int status = CarCrudSystem.delete(id);
            if(status > 0)
            {
                JOptionPane.showMessageDialog(jPanel3,"Car Deleted succesfully");
                this.setVisible(false);
                CarCrudSystemUI ui = new CarCrudSystemUI();
                ui.setAdminInfo(c_admin_name.getText());
                ui.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(jPanel3,"Sorry! Error Occured","Warning",JOptionPane.ERROR_MESSAGE);
            } 
    }//GEN-LAST:event_del_carActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        String t_id = u_id.getText();
        int id = Integer.parseInt(t_id);
        Car test_existence = CarCrudSystem.getCar(id);
        
        if(test_existence.getId() != 0)
        {
            //JOptionPane.showMessageDialog(jPanel3,"Record Added succesfully");
            u_id.setEditable(false);
            u_mar.setText(test_existence.getMar());
            
        }
        else
        {
            JOptionPane.showMessageDialog(jPanel3,"Ncin Not Found Error 404!!!","Warning",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_findActionPerformed

    private void u_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_carActionPerformed
        // TODO add your handling code here:
        String t_id = u_id.getText();
        String _mar = u_mar.getText();
        
        int id = Integer.parseInt(t_id);
        
        Car car = new Car(id,_mar);
        
        int status = CarCrudSystem.update(car);
            if(status > 0)
            {
                JOptionPane.showMessageDialog(jPanel3,"Car Updated succesfully");
                this.setVisible(false);
                CarCrudSystemUI ui = new CarCrudSystemUI();
                ui.setAdminInfo(c_admin_name.getText());
                ui.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(jPanel3,"Sorry! Error Occured","Warning",JOptionPane.ERROR_MESSAGE);
            } 
    }//GEN-LAST:event_u_carActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setHomeUsername(c_admin_name.getText());
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void v_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_carActionPerformed
        // TODO add your handling code here:
        String t_id = c_id.getText();
        int id = Integer.parseInt(t_id);
        
        Car car = CarCrudSystem.getCar(id);
        if(car.getId() == 0)
        {
            //error handling
            JOptionPane.showMessageDialog(jPanel3,"Sorry! Car Not Found Error 404","Warning",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            CarFileUI cFUI = new CarFileUI(car);
            cFUI.setAdminInfo(this.c_admin_name.getText());
            cFUI.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_v_carActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarCrudSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarCrudSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarCrudSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarCrudSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarCrudSystemUI().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_car;
    private javax.swing.JLabel c_admin_name;
    private javax.swing.JTextField c_id;
    private javax.swing.JTable cars_data;
    private javax.swing.JButton del_car;
    private javax.swing.JButton find;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mark;
    private javax.swing.JLabel pic;
    private javax.swing.JButton reset;
    private javax.swing.JButton u_car;
    private javax.swing.JTextField u_id;
    private javax.swing.JTextField u_mar;
    private javax.swing.JButton u_res;
    private javax.swing.JButton v_car;
    // End of variables declaration//GEN-END:variables
}
