/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cars;

import clients.ClientCrudSystem;
import static java.nio.file.Files.list;
import static java.util.Collections.list;
import javax.swing.table.DefaultTableModel;
import rent.Rent;
import rent.RentCrudSystem;

/**
 *
 * @author Med Amine Ben Ammar
 */
public class CarFileUI extends javax.swing.JFrame {

    /**
     * Creates new form CarFileUI
     * @param car
     */
    public CarFileUI(Car car) {
        initComponents();
        c_id.setEditable(false);
        c_mark.setEditable(false);
        
        
        String s_id = Integer.toString(car.getId());
        c_id.setText(s_id);
        c_mark.setText(car.getMar());
        
        DefaultTableModel model = (DefaultTableModel) v_car.getModel();
        int i = 0;
      
            
        for(Rent list:RentCrudSystem.getAllRentsByID(car.getId()))
        {
            i++;
            
            String lname = ClientCrudSystem.getClient(list.getNcin()).getLname();
            String fname = ClientCrudSystem.getClient(list.getNcin()).getFname();
            int tel = ClientCrudSystem.getClient(list.getNcin()).getTel();
            Object[] row = { i, list.getNcin(), fname, lname, tel, list.getDate(), list.getNbd(), list.getPd(), list.getNbd()*list.getPd() };
            model.addRow(row);
        }
        
    }

    private CarFileUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    public void setAdminInfo(String name)
    {
        this.c_admin_name.setText(name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        v_car = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c_mark = new javax.swing.JTextField();
        c_id = new javax.swing.JTextField();
        pic = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        c_admin_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Ncin", "First Name", "Last Name", "Tel", "Date", "Number Of Days", "Price Per Day", "Price"
            }
        ));
        jScrollPane1.setViewportView(v_car);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 660, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 660, 310));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mark : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("ID : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 50, 30));
        getContentPane().add(c_mark, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 130, 40));
        getContentPane().add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 40));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_pic.png"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 70));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("Admin Name : ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, 60));

        c_admin_name.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        c_admin_name.setText("jLabel12");
        getContentPane().add(c_admin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 110, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 70, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        CarCrudSystemUI cUI = new CarCrudSystemUI();
        cUI.setAdminInfo(c_admin_name.getText());
        this.setVisible(false);
        cUI.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarFileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarFileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarFileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarFileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CarFileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c_admin_name;
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField c_mark;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pic;
    private javax.swing.JTable v_car;
    // End of variables declaration//GEN-END:variables
}
