/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clients;

import authentication.Home;
import cars.CarCrudSystem;
import javax.swing.table.DefaultTableModel;
import rent.Rent;
import rent.RentCrudSystem;

/**
 *
 * @author Med Amine Ben Ammar
 */
public class ClientFileUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientFileUI
     */
    public ClientFileUI(Client clt) {
        initComponents();
        String s_ncin = Integer.toString(clt.getNcin());
        String s_fname = clt.getFname() + " " + clt.getLname();
        String s_tel = Integer.toString(clt.getTel());
        String s_adr = clt.getAdr();
        f_ncin.setText(s_ncin);
        f_fname.setText(s_fname);
        f_tel.setText(s_tel);
        f_adr.setText(s_adr);
        
        f_ncin.setEditable(false);
        f_fname.setEditable(false);
        f_tel.setEditable(false);
        f_adr.setEditable(false);
        
        DefaultTableModel model = (DefaultTableModel) v_clt.getModel();
        int i = 0;
      
            
        for(Rent list:RentCrudSystem.getAllRentsByNcin(clt.getNcin()))
        {
            i++;
            String mar = CarCrudSystem.getCar(list.getId()).getMar();
            Object[] row = { i, list.getId(), mar, list.getDate(), list.getPd(), list.getNbd(), list.getPd() * list.getNbd() };
            model.addRow(row);
        }
    }

    private ClientFileUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    public void setAdminInfo(String name)
    {
        this.c_admin_name.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        v_clt = new javax.swing.JTable();
        pic = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        c_admin_name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        f_adr = new javax.swing.JTextField();
        f_ncin = new javax.swing.JTextField();
        f_fname = new javax.swing.JTextField();
        f_tel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_clt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "ID", "Mark", "Date", "Number Of Days", "Price Per Day", "Price"
            }
        ));
        jScrollPane1.setViewportView(v_clt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 650, 280));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_pic.png"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 70));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("Admin Name : ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, 60));

        c_admin_name.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        c_admin_name.setText("jLabel12");
        getContentPane().add(c_admin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 110, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Retour");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 60, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 70));

        jLabel2.setText("Adress :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 60, 30));

        jLabel4.setText("Ncin :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 30));

        jLabel5.setText("Full Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 30));

        jLabel6.setText("Tel :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 60, 30));
        getContentPane().add(f_adr, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 30));

        f_ncin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_ncinActionPerformed(evt);
            }
        });
        getContentPane().add(f_ncin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 30));
        getContentPane().add(f_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 140, 30));
        getContentPane().add(f_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ClientCrudSystemUI cltUI = new ClientCrudSystemUI();
        cltUI.setAdminInfo(c_admin_name.getText());
        this.setVisible(false);
        cltUI.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void f_ncinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_ncinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_ncinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c_admin_name;
    private javax.swing.JTextField f_adr;
    private javax.swing.JTextField f_fname;
    private javax.swing.JTextField f_ncin;
    private javax.swing.JTextField f_tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pic;
    private javax.swing.JTable v_clt;
    // End of variables declaration//GEN-END:variables
}
